image: python:latest

before_script:
  - python --version
  - pip --version

run:
  script:
    - pip install build twine
    - python -m build
    - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - TWINE_USERNAME=__token__ TWINE_PASSWORD=${PYPI_PASSWORD} python -m twine upload dist/*
  only:
    - tags
