image: python:latest

before_script:
  - python --version
  - pip --version

run:
  script:
    - pip install build twine
    - python -m build
    - python -m twine upload dist/* --username gitlab-ci-token --password $CI_JOB_TOKEN
  only:
    - tags
